### ISSUE TITLE
Make rpath optional

### ISSUE THREAD

**Issue by ged** [ged/ruby-pg#183]
**[Original report](https://bitbucket.org/ged/ruby-pg/issue/183) by Vít Ondruch (Bitbucket: [vo_x](https://bitbucket.org/vo_x), ).**

----------------------------------------

As a resolution of #146, you added explicitly the -rpath option. While I understand this solves some issues, it causes issues for rubygem-pg Fedora package, since Fedora discourages usage or rpaths. I would be glad, if this change could be optional or reverted and the fix is applied where it belongs [2].

[1] https://fedoraproject.org/wiki/Packaging:Guidelines#Beware_of_Rpath
[2] https://fedoraproject.org/wiki/Packaging:Guidelines#Alternatives_to_Rpath

**Comment by junaruga** [comment]
@ged Why is this ticket closed?

I tested this old issue on the latest master branch 4419c2eea9ba95412b6f9424c29e7f8805160164 with the ruby configured with `./configure --enable-mkmf-verbose` on Fedora Linux 42.

The testing log is below.

My environment:

```
$ which ruby
~/.local/ruby-4.1.0dev-debug-dcfbbdc38c-openssl-4.0.0-dev-1cb0d36b39/bin/ruby

$ ruby -v
ruby 4.1.0dev (2026-01-08T09:48:38Z master dcfbbdc38c) +PRISM [x86_64-linux]

$ sudo dnf install libpq-devel

$ bundle config set path vendor/bundle

$ bundle install
```

I ran the following command. And I still can see the rpath `-Wl,-rpath,/home/jaruga/.local/ruby-4.1.0dev-debug-dcfbbdc38c-openssl-4.0.0-dev-1cb0d36b39/lib`, `-Wl,-rpath,/usr/lib64`, `-Wl,-rpath,/home/jaruga/.local/ruby-4.1.0dev-debug-dcfbbdc38c-openssl-4.0.0-dev-1cb0d36b39/lib`.

```
$ bundle exec rake compile
...
gcc -shared -o pg_ext.so gvl_wrappers.o pg.o pg_binary_decoder.o pg_binary_encoder.o pg_cancel_connection.o pg_coder.o pg_connection.o pg_copy_coder.o pg_errors.o pg_record_coder.o pg_result.o pg_text_decoder.o pg_text_encoder.o pg_tuple.o pg_type_map.o pg_type_map_all_strings.o pg_type_map_by_class.o pg_type_map_by_column.o pg_type_map_by_mri_type.o pg_type_map_by_oid.o pg_type_map_in_ruby.o pg_util.o -L. -L/home/jaruga/.local/ruby-4.1.0dev-debug-dcfbbdc38c-openssl-4.0.0-dev-1cb0d36b39/lib -Wl,-rpath,/home/jaruga/.local/ruby-4.1.0dev-debug-dcfbbdc38c-openssl-4.0.0-dev-1cb0d36b39/lib -L/usr/lib64 -Wl,-rpath,/usr/lib64 -L. -fstack-protector-strong -rdynamic -Wl,-export-dynamic -Wl,--no-as-needed -Wl,--compress-debug-sections=zlib    -Wl,-rpath,/home/jaruga/.local/ruby-4.1.0dev-debug-dcfbbdc38c-openssl-4.0.0-dev-1cb0d36b39/lib -L/home/jaruga/.local/ruby-4.1.0dev-debug-dcfbbdc38c-openssl-4.0.0-dev-1cb0d36b39/lib -lruby -lpq  -lm -lpthread  -lc
...
```

Maybe the following logic can be skipped in Linux case, since the logic's comment says the logic is for MacOS-X.

https://github.com/ged/ruby-pg/blob/4419c2eea9ba95412b6f9424c29e7f8805160164/ext/extconf.rb#L221-L226

**Comment by junaruga** [comment]
Sorry I might make mistake. I needed to test this on Fedora pg gem RPM package (rubygem-pg).

**Comment by larskanis** [comment]
That code was introduced [13 years ago](https://github.com/ged/ruby-pg/commit/2242f36594714da87c04a69d31b2cb6c199c8e17). I think it can be removed now, since this was an issue in an old ruby version. If the rpath is configured in ruby , then `dir_config` will use it, otherwise it shouldn't. I'll open a PR for that.

**Comment by junaruga** [comment]
@larskanis Okay. Thanks for your working to open the PR. That's great.
