### ISSUE TITLE
Do you follow SemVer? if yes, can you mention it in README?

### ISSUE THREAD

**Issue by ged** [ged/ruby-pg#273]
**[Original report](https://bitbucket.org/ged/ruby-pg/issue/273) by Praveen Arimbrathodiyil (Bitbucket: [pravi](https://bitbucket.org/pravi), GitHub: [pravi](https://github.com/pravi)).**

----------------------------------------

Many libraries already responded positively to similar requests https://wiki.debian.org/Teams/Ruby/UpstreamPledge

**Comment by dgpokl** [comment]
May I ask for some clarification on how this project uses semver (perhaps @ged or @cbandy would like to comment) ?

Version 1.3.0 of pg [dropped support for several ruby versions](https://github.com/ged/ruby-pg/blob/master/History.rdoc#label-v1.3.0+-5B2022-01-20-5D+Michael+Granger+-3Cged-40FaerieMUD.org-3E). Is my understanding of semver just wrong? I thought breaking changes merited a major version number increment (e.g. that would be a "2.0.0").

The only thing I can think of is that perhaps from some points of view, dropping support for an OS, language version, etc. could be considered not a "change to **this product's** public API" and thus not 'count' by the semver '[definitions](https://semver.org/).' I just didn't initially think that was the prevailing approach, because I think of language version/framework version compatibility as one of the basic things I look to semver to answer.

Currently I'm wondering if I should pin pg to allow patch versions only (or a specific patch version?) as the only way to be sure that a `bundle update` doesn't pull down an incompatible pg version, rather than allowing minor versions, as is my common practice.

Your thoughts would be greatly appreciated regardless of whether I'm getting this wrong :)

**Comment by ged** [comment]
Yes, I would say that this is addressed by a Semver FAQ: "[What should I do if I update my own dependencies without changing the public API?](https://semver.org/#what-should-i-do-if-i-update-my-own-dependencies-without-changing-the-public-api)"

The relevant bits:
> That would be considered compatible since it does not affect the public API. Software that explicitly depends on the same dependencies as your package should have their own dependency specifications and the author will notice any conflicts.

I do appreciate your philosophical point, but a major version bump in one of your dependencies can cause quite a lot of churn, especially if your project also includes other dependencies which have their own dependencies on (previous major version of) the library in question.

We do try to keep the `required_ruby_version` in the gem up-to-date, which should at least guard installation under incompatible versions of Ruby. Postgres version is another matter, but that's what the guards in `extconf` are for I suppose.

**Comment by dgpokl** [comment]
Thanks so much @ged for the detailed response, and in just a couple hours at that! It's helpful to know that is the reason for that decision.

Also, I didn't remember that that required Ruby version was in the Gemspec. I agree that should help.
