### ISSUE TITLE
No read-timeout support; deliberate omission or just overlooked feature?

### ISSUE THREAD

**Issue by jeffdoering** [ged/ruby-pg#324]
While ruby-pg supports libpq's `connect_timeout` as well as other keep-alive tuning options; it appears that a general network read-timeout is not supported. This is a bit surprising as keep-alive options tend to have platform-specific limitations while read-timeouts provide a general defense mechanism against non-responsive servers. Even if keep-alive is ideal; why not support read-timeout as well?

Is there a specific deliberate reason this is omitted or is it a reasonable feature request?

It appears that `pg_conn_async_exec` for example could support a timeout if the `pg_conn_block` call passed an optional timeout rather than always passing `NULL` options. I'm not sure how many places would need to be updated for consistent timeout support.

At this point I'm looking for feedback and confirmation on these observations to understand if this is a limitation or if I'm overlooking an existing solution.

**Comment by larskanis** [comment]
> Is there a specific deliberate reason this is omitted or is it a reasonable feature request?

I think it's due to the fact that a read timeout is an asymmetric decision. Since the client aborts the communication, but the server isn't aware of it, the TCP protocol comes in an undefined state and is therefore no longer usable in a safe way.

You could implement a read timeout by making use of the async pg API. The `conn.block` method can be called with a timeout. But implementing a read timeout based on it, IMHO doesn't make much sense, since PostgreSQL provides many timeout related settings. I therefore don't plan to extend the rest of the API by such an option.

There are the [keep-alive settings](https://www.postgresql.org/docs/12/libpq-connect.html#LIBPQ-PARAMKEYWORDS) you already mention, but you can also set [several server settings](https://www.postgresql.org/docs/12/runtime-config-client.html#GUC-STATEMENT-TIMEOUT). The server settings can be set per `SET` SQL command, but can also be passed per connection option or in `database.yml` like:
```ruby
c = PG.connect options: "-c statement_timeout=1s"
 => #<PG::Connection:0x000055653cd613d8> 
c.exec("select pg_sleep(2)").to_a
 Traceback (most recent call last):
         1: from (irb):3:in `async_exec'
 PG::QueryCanceled (ERROR:  canceling statement due to statement timeout)
```

Since we try to follow the libpq semantics closely, you could ask the PostgreSQL people for a read timeout. But I think it's intentionally not present.

**Comment by jeffdoering** [comment]
Thanks for the confirmation. I understand that it's asymmetric and leaves the server processing. That's a standard design trade-off for TCP-based connections where keep-alive are the only firmer guarantee that both sides find out about the dead connection. It doesn't solve the full problem the keep-alive do; but it can provide protection in cases where keepalives are disabled or under-supported by OS, etc. Servers can also use read timeouts when they know the client should be actively sending data (e.g. when a partial application message has been received). They can also use read-timeouts to enforce policies that limit the impact of slow-data DOS problems where the connection is alive but data is returned too slowly (of course the server is probably natively using async data processing anyway which makes timeout implementation a bit different). They obviously cannot use read-timeouts to detect whether an idle connection is dead.

Postgres server-side timeouts are a different control as they save resources on the server-side (which is great) but they don't address issues with connectivity between the client and server at all.

Other DB clients (e.g. mysql2 ruby client: https://github.com/brianmario/mysql2/blob/f8560c551bf1999baf7df43290e8f89471e77af4/ext/mysql2/client.c#L666, Oracle JDBC drivers, etc) tend to support read-timeouts which is why I was surprised to not find them in ruby-pg. I agree that the async processing model makes it possible to use them; but that making them work with ActiveRecord would be easiest if they were natively supported by the standard calls.

Again; thank you for confirming the current behavior and reasoning. Understanding the design was my main motivation at this point.
