### ISSUE TITLE
Make pg more Ruby-3.0 fiber scheduler friendly

### ISSUE THREAD

**Issue by larskanis** [ged/ruby-pg#342]
This was raised by @ioquatix in https://github.com/ffi/ffi/issues/797#issuecomment-654153362 :

In order to support the upcoming Ruby 3.0 fiber scheduler, you need to do only one thing:

When you would call a blocking function that does I/O, instead call `IO#wait_readable` or `IO#wait_writable` respectively.

If you want to support Ruby 2.x, then allow the user to inject a custom IO class, which responds to `.new` and implements `#wait_readable` and `#wait_writable`.

You can check how to do it here:

https://github.com/socketry/db-postgres/blob/6fbdd03dd6b04c57c5b7995b60e3f626c674e609/lib/db/postgres/native/connection.rb#L106-L139

We will be augmenting the C interface with some improvements for invoking `IO#wait_readable/wait_writable` but it hasn't landed yet.

Feature description is here: https://bugs.ruby-lang.org/issues/16786

**Comment by ioquatix** [comment]
Awesome, let me know if I can provide any further help :)

cc @tenderlove

**Comment by jasl** [comment]
I just wrote a PoC

```ruby
class PG::Connection
	module FiberScheduler
		[
			:exec, :query, :exec_params, :prepare,
			:exec_prepared, :describe_portal, :describe_prepared
		].each do |method|
			module_eval <<-CODE, __FILE__, __LINE__ + 1
				def #{method}
					Fiber.scheduler.io_wait(socket_io, IO::WRITABLE, 5)
					super
					Fiber.scheduler.io_wait(socket_obj, IO::READABLE, 5)
				end
			CODE
		end
	end
	include FiberScheduler
end
```

It's dirty, but pass tests (set `evt` as Fiber scheduler in `spec_helpers` then disable `connection_spec` and `connection_sync_spec` temporary)

Any directive or guidance?

A question, I'm stucking on adding `evt` to Gemfile but failed to require it for 10 minutes, then I found I need to declare it in `Rakefile`, any historical reason for using `Hoe` not standard `Gemfile`?

**Comment by jasl** [comment]
@larskanis @ioquatix could you take a look PR #364 ?

I'm done a PoC:

- Add a `PG::Connection.use_fiber=` method to enable fiber scheduler support
  - Require Ruby version > 3.0
  - Require `PG::Connection.async_api = true`
- Change behavior of `PG::Connection.async_api = false`
  - It will raise error if Fiber Scheduler set, because the scheduler leading blocking IO will stucking,
  - You have to `Fiber.set_scheduler nil` before set `async_api` false
  - Set `async_api` false also set `use_fiber` false
- Update `rake spec`, test both with and without fiber on Ruby 3.0 (ruby-head)

Todo:

- few test cases disabled for now, becuase I don't know how to fix yet

Help needed:

- I don't know the API design, naming, coding style satisfied maintainers
- I don't know my work is right and covered all cases, although test cases pass

**Comment by ioquatix** [comment]
If the scheduler is set you should use non-blocking event driven I/O. There shouldn't be a need to add `PG::Connection.use_fiber=`.

**Comment by jasl** [comment]
> If the scheduler is set you should use non-blocking event driven I/O. There shouldn't be a need to add `PG::Connection.use_fiber=` or any other "configuration".

You're right, I revisit the problem I first met, the test hanging on https://github.com/ged/ruby-pg/blob/master/spec/pg/connection_spec.rb#L1670-L1695

**Comment by jasl** [comment]
One pain point I've met is somewhere hanging when fiber scheduler enabled, but I don't know where.
Any sugguest about debugging this situation?

**Comment by ioquatix** [comment]
`Fiber#backtrace` may help. If you use async you can print out all the backtraces using `Reactor#print_hierarchy`.
