### ISSUE TITLE
Rethinking CI?

### ISSUE THREAD

**Issue by junaruga** [ged/ruby-pg#362]
(I posted this topic on the MySQL Ruby binding mysql2: https://github.com/brianmario/mysql2/issues/1149 .)

Do you know the Travis following announcements about their changes?
https://blog.travis-ci.com/oss-announcement
https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing

> The upcoming pricing change will affect those of you who are:
> Building on a public repositories only

When I am running ruby-pg Travis CI on my forked repository now, it is very slow now. It takes time to even start. You can see [the log](https://travis-ci.org/github/junaruga/ruby-pg/builds/749618964).

I see the Ruby project recently migrated the most cases to GitHub Actions remaining a few non-x86_64 jobs in Travis.
https://github.com/ruby/ruby/blob/f3c19ddfbcfde63505a34b7a5b3a640f23b22dc0/.travis.yml#L199-L204

So, what do you think about migrating our CI from Travis to GitHub Actions or an alternative CI?

**Comment by larskanis** [comment]
https://travis-ci.org is slow these days and deprecated long time ago. But https://travis-ci.com is fast as ever. I migrated a bunch of projects from .org to .com and it worked flawlessly with a single click. I didn't request any OSS support as offered in [the anouncement](https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing#building-on-a-public-repositories-only), but I'm confident that they won't deny.

On the other hand I don't have any issues with Github actions. It's just that it needs some effort to implement it there.

Last but not least both options (travis-ci.com and Github actions) must be done by @ged, since he's the project owner.

**Comment by junaruga** [comment]
@larskanis I saw your PR about starting GitHub Actions. Thanks!

> Last but not least both options (travis-ci.com and Github actions) must be done by @ged, since he's the project owner.

OK. Let's wait the response from  @ged.

**Comment by ged** [comment]
I'd be into moving things into Github. What do I need to do?

**Comment by junaruga** [comment]
@ged OK. I think we need to do some things.

1. First maybe you can enable the GitHub Actions by checking [this repo's Actions tab](https://github.com/ged/ruby-pg/actions).
2. Then we need to review #374 including `.github/workflows/*.yml` file.
3. Then we might be able to migrate other cases in the current CIs into GitHub Actions too. I think the good examples might be [rspec-core](https://github.com/rspec/rspec-core/tree/main/.github/workflows) and [mysql2](https://github.com/brianmario/mysql2/tree/master/.github/workflows) gem's repositories.
