### ISSUE TITLE
Merge of python and ruby PostgreSQL drivers

### ISSUE THREAD

**Issue by larskanis** [ged/ruby-pg#449]
Never thought about the need to write drivers again and again for every programming language? Why not use one and the same code base for multiple language?

          Because it doesn't work! 😌

But it could! Just use pycall!

          We make the switch! In pg-1.4.2022 ! 😳

          Be prepared and install python today! 😉

**Comment by ged** [comment]
This will be so much easier. Thanks for doing this!

**Comment by ryanb** [comment]
@ariccio this is a message that only shows up on April 1. 😉

**Comment by ariccio** [comment]
LMAO
*chef's kiss*

**Comment by doconnor-clintel** [comment]
Yes, this has caused problems for deployment pipelines in the wild. While our [very ancient] tools probably shouldn't be so fragile as to break with content like this, the real world impact has been engineering time figuring this out.

I'd discourage you from this sort of thing if possible; considering the scope and adoption of the gem; plus the combination of automated build and dependency tools.
Putting something like this into the changelog itself; rather than _code which is executed by tools like bundler_ would likely have had less of an impact.

**Comment by ariccio** [comment]
Wait, something in your tool chain actually broke? I was worrying that I would actually need to make sure my build pipeline had the python environment setup, not having problems right now... Kinda why I thought it was excellent.

What was your tool doing? Comparing the raw console output? Sounds to me like this gem just did some unintentional QA for you 🤣

**Comment by pavels** [comment]
> Yes, this has caused problems for deployment pipelines in the wild. While our [very ancient] tools probably shouldn't be so fragile as to break with content like this, the real world impact has been engineering time figuring this out for what is basically a supply chain attack.
> 
> I'd discourage you from this sort of thing if possible; considering the scope and adoption of the gem; plus the combination of automated build and dependency tools. Putting something like this into the changelog itself; rather than _code which is executed by tools like bundler_ would likely have had less of an impact.

Disclaimer: i am not affiliated with the author, just saw the message and followed the link:

IMHO

a) it is funny
b) see https://en.wikipedia.org/wiki/Chaos_engineering - in other words, things like this actually help us as and the industry as a whole to be more resilient towards disruption. Your tools should not break under this conditions and so does others. Let's make computing less fragile, one system at a time :)
c) "basically a supply chain attack" - well, it is actually not - but you can take this as a security drill - just keep in mind the real attack will not have giant message with a link in it.

**Comment by doconnor-clintel** [comment]
> Sounds to me like this gem just did some unintentional QA for you

and

> a) it is funny


Yeah. So here's the problem with that - chaos engineering and similar are intentional, opt in choices. Our organisation chose to use what they regarded as a reasonably well trusted public dependency of high enough quality for database connectivity; but did *not* opt in to this methodology.

While this was caught very early on in the piece (why I'm here pointing out this was a particularly silly thing to do; rather than dealing with spot fires); it incurs a engineering time and effort to banish the deliberately tainted dependency that could be better spent elsewhere.

I say this not from simply a _cost_ perspective, but from a _quality, risk and safety_ perspective.

**Total downloads of this gem:**
180,716,082

**For this version:**
18,690 (in 24 hours!)

If you assume 1 in 500 of those encounter a bug, and then 5% of those slip through a code review due to human error, then perhaps 5% more of those slip through CI/CD gates; you end up with:

(18690 * 30 days) / 500 * 0.05 * 0.05 = ~2.8 deployments/installs/etc a month broken by this; or up to ~33 a year.

**What is the likelyhood that any of these industries using Ruby + Postgres?**

- Healthcare
- Law enforcement
- Defence
- Finance
- Security
- Property

What's the likelyhood of harm occurring to people if systems in those areas experience problems? Small, but not zero. Where if this had simply been done in a changelog or as some another announcement, that risk would be a lot closer to zero.

**Comment by larskanis** [comment]
Thank you all who participated in this small April Fool, so far! I hope you recognized it as a joke and enjoyed it! Please don't forget the [philosophy of ruby](https://en.wikipedia.org/wiki/Ruby_(programming_language)#Semantics_and_philosophy):

> Matsumoto has said that Ruby is designed for programmer productivity and fun, following the principles of good [user interface](https://en.wikipedia.org/wiki/User_interface) design.[[81]](https://en.wikipedia.org/wiki/Ruby_(programming_language)#cite_note-informit-81) At a Google Tech Talk in 2008 Matsumoto further stated, "I hope to see Ruby help every programmer in the world to be productive, and to enjoy programming, and to be happy. That is the primary purpose of Ruby language."

You can feel certain, that we'll continue the good work to develop and maintain this important database driver. And for sure, pg-1.4.x will bring new improvements, that I don't know today, but it will certainly not require you to install python to run ruby!

@doconnor-clintel Don't panic! Look into the [commit](https://github.com/ged/ruby-pg/commit/f49d4404ec0a03cd11384578b7ea38ad8f36127e) and see that the message comes out today only. Just settle back and smile! :smiley:

**Comment by pavels** [comment]
@doconnor-clintel

and here is the problem, after years and years of talks about dependency safety and supply chain security there are still people complaining that such a small thing as this joke has impacted them.

`it incurs a engineering time and effort to banish the deliberately tainted dependency that could be better spent elsewhere` - i don't think so - i think the time spent on fixing your CI, so things like this don't break it is time well spent. But of course it is 100% your decision on where to spend your time. I just believe that blaming maintainers of this package because you CI got broken because of this change is silly.

Also saying that the maintainers are responsible for problems in  Healthcare ... is silly. If you are in one of the mentioned industries and this thing disrupted your operations by any means than that is scary. 

'What's the likelyhood of harm occurring to people if systems in those areas experience problems?' - than the full blame is on the engineers, who made such a system. If you are downloading dependencies "from the internet" without proper checks and at the same time you are dealing with systems, that can actually harm people i case of malfunction, than you are doing it wrong. Very wrong. And you should stop.

**Comment by larskanis** [comment]
Oh sorry @pavels I deleted you comment by accident!

**Comment by simi** [comment]
Damn, you got me for a minute @larskanis. :partying_face:

**Comment by pavels** [comment]
@larskanis whatever :smile: so be it

I just really like these small things that happens here and there (like the (in)famous message after installing https://github.com/jnunemaker/httparty ) and wanted to voice support. And i still strongly believe that we should strive to build more resilient systems that don't tend to break with changes like this.

:heart:

**Comment by yshmarov** [comment]
😆

**Comment by casi** [comment]
That's why I hate the first of April with all my heart. Okay, one of the reasons. ;)

**Comment by ChoHag** [comment]
Why would you make a production deployment system this fragile? Who in their right mind would then use such a monstrosity in healthcare? Fix your own system don't expect the world to do it for you.

It is, indeed, funny. Finally an April fool doing it right.

**Comment by thepeoplesbourgeois** [comment]
> I say this not from simply a cost perspective, but from a quality, risk and safety perspective.

I too believe that it is better from a quality, risk, and safety perspective for brittle, [unexamined](https://en.wikipedia.org/wiki/The_unexamined_life_is_not_worth_living) systems to remain that way, up until (& after?) a truly malicious attack or large-scale natural disaster completely levels said systems, resultantly toppling civilization as we know it.

**Comment by moapwr** [comment]
chaos engineering and similar are intentional, opt in choices

pulling code from the interwebs is considered an opt-in to chaos engineering

**Comment by jirihradil** [comment]
Ha. Ha.

**Comment by rchasman** [comment]
Great stuff! Thank you for maintaining this Gem and having fun with it!
