### ISSUE TITLE
inheritence issue with pg version >= 1.3.0

### ISSUE THREAD

**Issue by KiriakosGeorgiou** [ged/ruby-pg#478]
Up until pg version 1.2.3 I could inherit from PG::Connection like this:

```
class PGx::Connection < PG::Connection
  def initialize(*args)
  ....
  end
end
```

and my derived class' initialize() would be called first, as expected.  Starting with pg 1.3.0 onward, the derived class' initialize() is not called at all.  I tried for a couple of days to get to the bottom of this, without success.  Can you steer me in the right direction?

I use ruby 2.7.6

thanks!

**Comment by larskanis** [comment]
You're right, `PG::Connection#initialize` is no longer called since pg-1.3.

I made a change to `PG::Connection` which reactivates the call [here](https://github.com/larskanis/ruby-pg/commit/569f9eedb76cc49b6022f32c76c4cc1ada022eeb) but I'm not convinced, that this change should be merged. `initialize` might be called multiple times per call to `PG::Connection.new` and gets different arguments. `initialize` is more kind of internal method, not intended to be derived.

Can you please describe more about your use case for deriving `PG::Connection`?

**Comment by KiriakosGeorgiou** [comment]
My use case: I extended pg to provide logging, retrying and reconnecting.  Documentation is here: http://www.mockbites.com/articles/tech/pgx

**Comment by KiriakosGeorgiou** [comment]
No need to merge, I resolved this by adding to my derived class a new() and explicitly call the initialize() as follows:

```
def self.new(*args, &block)
    obj = allocate
    obj.send(:initialize, *args, &block) # initialize is a private instance method by default
    obj
end
```

**Comment by larskanis** [comment]
I think it's best to derive `PG::Connection.new` instead of `PG::Connection#initialize`. Also note that there are several alias methods: https://github.com/ged/ruby-pg/blob/master/lib/pg/connection.rb#L684-L687
