### ISSUE TITLE
How to Decode Numeric type to Ruby Integer?

### ISSUE THREAD

**Issue by pgundlupetvenkatesh** [ged/ruby-pg#483]
New to Postgres and ruby-pg. I am using `conn.type_map_for_results = PG::BasicTypeMapForResults.new(conn)` type cast and all our table columns(digits only) are Numeric type. How can I decode all Numeric type column values to Ruby Integer using `PG::TextDecoder::Numeric` decoder class? 

[PG::TextDecoder::Numeric](https://www.rubydoc.info/gems/pg/PG/TextDecoder/Numeric) decodes Postgres Numeric to Ruby BigDecimal

Ruby and Postgres versions -
Ruby v2.6.3
Postgres v14.2

**Comment by larskanis** [comment]
The default type en-/decoders of `PG::BasicTypeMapForResults` are [defined here](https://github.com/ged/ruby-pg/blob/43177058851c3f50c7d0bfeb331f545138bef000/lib/pg/basic_type_registry.rb#L215-L282). If the default mapping doesn't fit to your needs, there are plenty of ways to customize it. But it's difficult to help without further details about the tables and their use.

If you're new to ruby you should also have a look at ActiveRecord or Sequel since they are more high-level and database independent ways to use the PostgreSQL server. And you should update the ruby version.

**Comment by larskanis** [comment]
OK, after reading it twice, I probably got your issue. Mapping PostgreSQL type `numeric` to ruby `Integer` can be done be using your own type map like so:

```ruby
conn = PG.connect
regi = PG::BasicTypeRegistry.new.register_default_types
regi.alias_type 0, 'numeric', 'int4'
conn.type_map_for_results = PG::BasicTypeMapForResults.new(conn, registry: regi)
```

**Comment by larskanis** [comment]
PG::BasicTypeRegistry is documented here: https://deveiate.org/code/pg/PG/BasicTypeRegistry.html

**Comment by pgundlupetvenkatesh** [comment]
> OK, after reading it twice, I probably got your issue. Mapping PostgreSQL type `numeric` to ruby `Integer` can be done be using your own type map like so:
> 
> ```ruby
> conn = PG.connect
> regi = PG::BasicTypeRegistry.new.register_default_types
> regi.alias_type 0, 'numeric', 'int4'
> conn.type_map_for_results = PG::BasicTypeMapForResults.new(conn, registry: regi)
> ```

Thank you this was helpful.
