### ISSUE TITLE
Breaking change with conninfo_hash with 1.4.4

### ISSUE THREAD

**Issue by ankane** [ged/ruby-pg#490]
Hi, it looks there was recently a breaking change with the results of the `conninfo_hash` method (likely related to #485).

```ruby
require "pg"

p PG.connect("postgres://localhost/postgres").conninfo_hash.slice(:host, :port, :hostaddr)
```

1.4.4

```ruby
{:host=>"localhost,localhost", :port=>"5432,5432", :hostaddr=>"::1,127.0.0.1"}
```

1.4.3

```ruby
{:host=>"localhost", :port=>"5432", :hostaddr=>"::1"}
```

Ref: https://github.com/open-telemetry/opentelemetry-ruby-contrib/pull/142 and https://github.com/ankane/pgsync/issues/169

**Comment by cbandy** [comment]
I believe the OpenTelemetry code you linked is using the wrong methods to interrogate the active connection. The `conninfo` and `conninfo_hash` methods return information about the connection string (possible connections), while the `host`, `hostaddr`, `port`, etc methods return _the_ [one] current/active connection details.

**Comment by larskanis** [comment]
I agree with @cbandy - the right fix in both cases is to use PG::Connection#host and port instead of dedup the conninfo_hash.

It might be unexpected, to get a different conninfo_hash than arguments given to PG.connect, but we always have been adding some particular items to it by the pg.gem. New is that we resolve the host to multiple IP addresses as described in #485.

**Comment by ankane** [comment]
Thanks for the responses - will consider going that direction.
