### ISSUE TITLE
PG::Coder.new(hash) is deprecated

### ISSUE THREAD

**Issue by zhugexinxin** [ged/ruby-pg#523]
pg 1.5.0
rails 7.0.4.3
<img width="1252" alt="image" src="https://user-images.githubusercontent.com/42615243/233997365-08bcedd2-ef5d-4951-be42-274d88bf8c2f.png">

**Comment by 9mm** [comment]
Getting this too

**Comment by larskanis** [comment]
Don't worry about this warning! It is a deprecation warning in pg which has to be fixed in rails. Here is the related rails issue: https://github.com/rails/rails/issues/48046 
The warning will disappear with the next rails patch version.

**Comment by dogweather** [comment]
Maybe this should be logged, rather than a `puts`? (Apologies if that's what's happening.)

**Comment by a160v** [comment]
Hey folks,

The warning message you received is related to passing a hash to the new method of the decoder_class, which is likely a PG::Coder instance. The PG::Coder.new method was updated to use keyword arguments instead of a hash in Ruby 3.0, and the old syntax is now deprecated.

To fix the warning message, you should update the code to use keyword arguments instead of a hash when calling the new method of decoder_class. The issue happens in a line of def _update_typemap_for_default_timezone_:

replace
`@timestamp_decoder = decoder_class.new(@timestamp_decoder.to_h)`
with
`@timestamp_decoder = decoder_class.new(**@timestamp_decoder.to_h)`

By using the double splat operator (**), you can convert the hash returned by @timestamp_decoder.to_h into keyword arguments. This way, the new method of decoder_class receives the arguments in the updated syntax, and the deprecation warning should be resolved.

If you are using a version of Ruby earlier than 3.0, you can continue to use the hash syntax, but be aware that it is now deprecated and may be removed in future versions of Ruby.

**Comment by larskanis** [comment]
pg-1.5.3 marks the warnings as deprecation, so that they are suppressed at an ordinary rails run and shouldn't bother any longer.

**Comment by dogweather** [comment]
> pg-1.5.3 marks the warnings as deprecation, so that they are suppressed at an ordinary rails run and shouldn't bother any longer.

Thank you! This sounds like the right way to go.
