### ISSUE TITLE
Bad IAM Token against Amazon Aurora Postgres: Out of memory error

### ISSUE THREAD

**Issue by Navbryce** [ged/ruby-pg#546]
When I generate a "bad IAM token" (e.g., the user doesn't even exist) and try connect to my database with it, the driver throws an OOM error. I think this implies the driver is somehow mishandling the response.
```
async_connect_or_reset': out of memory (PG::ConnectionBad)
        from /src/bundle/ruby/3.1.0/gems/pg-1.4.5/lib/pg/connection.rb:760:in `connect_to_hosts'
```

Here's the error I expect, which I get in python with psycopg2 using the same IAM token that was generated in ruby:
```
 FATAL:  password authentication failed for user "non_existent_user"
```

Notably, if I use a non-IAM token formatted password (`foobar`), I get the expected error:
```
FATAL:  password authentication failed for user "non_existent_user" (PG::ConnectionBad)
```

I can try to investigate it on my end with maybe some pointers? Ruby (and database) drivers are far from my experience! I appreciate all the hard work put into maintaining this ❤️ ! I realize issue reports like this can be frustrating because there are a lot of confounding variables, sorry!

**Comment by larskanis** [comment]
Thank you for the kind words!

You cut the error output so that the line where the PG::ConnectionBad is thrown is missing. It's probably line 632, isn't it?

The code to establish a connection has changed quite a bit between pg-1.4 and pg-1.5. Could you please retry with pg-1.5.4?

A possible reason for different results compared to psycopg2 is that ruby-pg uses libpq's async API per default. It sometimes behaves somewhat different. Nevertheless it should return the correct error text. I'd like to reproduce this to investigate it a bit further. Is there a way to reproduce the error on my end?

**Comment by larskanis** [comment]
Closing due to no response.
