### ISSUE TITLE
Dereference of null in alloc_query_params

### ISSUE THREAD

**Issue by sminux** [ged/ruby-pg#580]
Hi there!
Static analyzer shows this warning:
After having been compared to a NULL value at 
https://github.com/ged/ruby-pg/blob/764f6d5457fe06b4b93cad1874134ef2bdfccb19/ext/pg_connection.c#L1277
pointer 'conv' is dereferenced at 
https://github.com/ged/ruby-pg/blob/764f6d5457fe06b4b93cad1874134ef2bdfccb19/ext/pg_connection.c#L1301

I can see the check of param_value before: if( NIL_P(param_value) ). It's somehow connected with 'conv'.
But It seems to be true positive. Should we check the 'conv' for null one more time?

**Comment by larskanis** [comment]
The memory management in `alloc_query_params()` is a bit complicated. I wrote it 10 years ago and since then there was no single change in this function.

The validity of `conv` is obviously too complicated for a static analyzer. It works like so:
If `conv` is `NULL`, then `pg_coder_enc_func()` assigns `pg_coder_enc_to_s()` to `enc_func`:
https://github.com/ged/ruby-pg/blob/64fe4c15d2ef6994cbddb1a15523075ecf3b07b5/ext/pg_coder.c#L504-L514
Then the function pointer `enc_func` is called with a `NULL` pointer as `this` (and that's probably what the static analyzer is complaining about):
https://github.com/ged/ruby-pg/blob/64fe4c15d2ef6994cbddb1a15523075ecf3b07b5/ext/pg_connection.c#L1301-L1305

So, if `conv` is `NULL` it is always the function `pg_coder_enc_to_s()` that is called; never any other encoder. I added a comment in 64fe4c15d2ef6994cbddb1a15523075ecf3b07b5 to warn about this exception in `pg_coder_enc_to_s()`. All other encoders can dereference the `this` pointer without `NULL` verification.
