### ISSUE TITLE
Feature request: AWS RDS IAM Authentication native support

### ISSUE THREAD

**Issue by matt-domsch-sp** [ged/ruby-pg#602]
Currently, one must use a password to authenticate to a Postgres server.  AWS RDS's implementation of Postgres allows one to use IAM Authentication, which uses a short-lived generated token in place of the password. 

https://github.com/haines/pg-aws_rds_iam is one attempt to provide this functionality.  This has the drawback that a new short-lived token is generated on every new connection, rather than re-using the short-lived generated token for its 15-minute lifetime.  This can lead to connection failures due to AWS rate limits on generating those tokens.

I'm proposing an incomplete solution here with request for guidance.  This solution retrieves and caches a token, reusing it for the lifetime of the token, then generates another.  Each host/port/user/region combination is cached separately. It's simpler than the above because it replaces the password immediately before establishing the connection by doing so in this gem directly, rather than having to hook all the possible paths a password could be needed via an external gem.

https://github.com/matt-domsch-sp/ruby-pg/commit/ef73bf7d2b2469d83e82aeea4bbe055ec81bc27d

One significant drawback to this approach is that I have not found a good way to add connection options that are only used by the gem, and not used or recognized by libpg, which does option validation.  Here I've avoided that by using environment variables, but that solution isn't optimal. I'd prefer to be able to set `:use_iam_authentication` (to invoke the functionality) and `:host_region` (a value required to generate the token) in the connection configuration iopts, and simply have them be ignored by methods that do not need to know about them.  Advise welcome please.

**Comment by larskanis** [comment]
Sorry for not answering earlier, but I don't want an implementation like #605 in ruby-pg. If it's implemented in libpq, then it's no problem - then it's not in my responsibility to maintain and check it. But in ruby-pg we would need proper tests that work both locally and in the CI without a lot of setup.

Architectural I also think that https://github.com/haines/pg-aws_rds_iam is the better approach. We can talk about easier hooks in ruby-pg, in order to plug-in IAM as authentication method for ruby-pg. But it should be in it's own repository.

**Comment by matt-domsch-sp** [comment]
Feature request for pg-aws_rds_iam filed. https://github.com/haines/pg-aws_rds_iam/issues/688
